lavc/videotoolboxenc: add ProRes support
FFmpeg/FFmpeg pull request #378
Opened 2021-12-17 00:05 UTC by rcombs

Also includes a variety of infrastructural improvements in the VideoToolbox encoder, and some format support improvements in swscale.

2021-12-19 17:55 UTC, kernrj requested changes

2021-12-19 17:55 UTC, kernrj commented on libavcodec/videotoolboxenc.c
> +        case AVCOL_SPC_RGB:
It would be clearer to set the matrix to NULL here (like the AVCOL_SPC_UNSPECIFIED case).

2021-12-19 17:55 UTC, kernrj commented on libavcodec/videotoolboxenc.c
> +        int chroma = (p != 0) && (!(desc->flags & AV_PIX_FMT_FLAG_ALPHA) || p + 1 != *plane_count);
This could be broken out into more variables to make the logic clearer. It took me a while to parse this.

2021-12-19 17:55 UTC, kernrj commented on libavcodec/videotoolboxenc.c
> +        size_t len = CMBlockBufferGetDataLength(buf);
The declaration should be at the beginning of the block.

2021-12-21 09:50 UTC, rcombs commented
@kernrj I re-pushed with your comments addressed. There are also several additional commits in the branch now; sorry, I'm just expecting them all to ultimately land at around the same time.

2021-12-23 01:00 UTC, merged

2021-12-23 08:02 UTC, TimothyGu commented
(To be sure, I didn't merge this PR on GitHub or otherwise. But I maintain the FFmpeg/FFmpeg mirror, and it appears that the patches have been applied [upstream](https://git.ffmpeg.org/gitweb/ffmpeg.git/shortlog/3e00b9e395fd6bc1d79e0e30885b7ccc2c9ecbba) with the same commit hashes.)

2021-12-23 08:23 UTC, rcombs commented
Probably because your account pushed the commits to ffmpeg/ffmpeg.